/*
 * This file is generated by jOOQ.
 */
package org.robertux.financeAnalytics.FinanceAnalyticsServer.data.entities;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import org.robertux.financeAnalytics.FinanceAnalyticsServer.data.entities.tables.Account;
import org.robertux.financeAnalytics.FinanceAnalyticsServer.data.entities.tables.Transaction;
import org.robertux.financeAnalytics.FinanceAnalyticsServer.data.entities.tables.User;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCOUNT_PKEY = Indexes0.ACCOUNT_PKEY;
    public static final Index TRANSACTION_PKEY = Indexes0.TRANSACTION_PKEY;
    public static final Index CUSTOMER_PKEY = Indexes0.CUSTOMER_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACCOUNT_PKEY = Internal.createIndex("account_pkey", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.NUMBER }, true);
        public static Index TRANSACTION_PKEY = Internal.createIndex("transaction_pkey", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.ID }, true);
        public static Index CUSTOMER_PKEY = Internal.createIndex("customer_pkey", User.USER, new OrderField[] { User.USER.ID }, true);
    }
}
